apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: test-blur-image
spec:
  predictor:
    containers:
      - name: kserve-container
        image: yangwenz/test-blur-image:v1
