build:
  python_version: "3.10"
  cuda: "11.7"

  # a list of packages in the format <package-name>==<version>
  python_packages:
    - "kservehelper>=1.0.8"
    - "torch>=2.0"
    - "transformers~=4.27.1"
    - "diffusers==0.14.0"
    - "accelerate"

# The name given to built Docker images
image: "yangwenz/stable-diffusion:v3"

# model.py defines the entrypoint
entrypoint: "model.py"