build:
  python_version: "3.10"
  cuda: "11.7"

  # a list of ubuntu apt packages to install
  system_packages:
    - "libglib2.0-0"
    - "libxext6"

  # a list of packages in the format <package-name>==<version>
  python_packages:
    - "kservehelper>=1.0.8"
    - "torch>=2.0"
    - "transformers~=4.27.1"
    - "diffusers"
    - "accelerate"
    - "safetensors"
    - "omegaconf"
    - "invisible-watermark>=0.2.0"

# The name given to built Docker images
image: "yangwenz/stable-diffusion-xl:v1"

# model.py defines the entrypoint
entrypoint: "model.py"