apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: stable-diffusion-xl
spec:
  predictor:
    containerConcurrency: 1
    minReplicas: 1
    maxReplicas: 1
    containers:
      - name: kserve-container
        image: yangwenz/stable-diffusion-xl:v1
        env:
          # The following values are defaults which may be changed as needed
          - name: MODEL_PATH
            value: "/mnt/models/stable-diffusion-xl-base-1.0"
          - name: REFINER_PATH
            value: "/mnt/models/stable-diffusion-xl-refiner-1.0"
          # KServe mounts the PVC at /mnt/models/
          - name: STORAGE_URI
            value: pvc://model-store-pvc
          - name: USE_REFINER
            value: "1"
        resources:
          requests:
            cpu: 4
            memory: 20Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 4
            memory: 20Gi
            nvidia.com/gpu: 1
